site_name: "MyService"
site_description: "MyService"
repo_url: https://github.com/gianfragolo/MyService
edit_uri: edit/master/docs

nav:
  - "Home": "index.md"
  - "Getting Started": "getting-started.md"
  - "Code of Conduct": "CODE_OF_CONDUCT.md"
  - "Readme": "readme.md"

plugins:
  - techdocs-core
