apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice
  labels:
    backstage.io/kubernetes-id: myservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice
  template:
    metadata:
      labels:
        app: myservice
        backstage.io/kubernetes-id: myservice
    spec:
      containers:
        - image: lucamilan/myservice:latest
          imagePullPolicy: Always
          name: myservice
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:5000"
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 128Mi
